from .env import (
    DEBUG,
    MAX_TOKENS,
    TEMPERATURE,
    LANGUAGE,
    PRIOR_CONVERSAION_SIZE,
    CONTEXT_HISTORY_SIZE,
    OPEN_WINDOW_DIRECTION,
    OPEN_WINDOW_SIZE,
    OPENAI_API_MODEL_NAME,
    ALLOWED_MODELS,
    CONTEXT_FILE_PATH,
    PROMPT_FILE_PATH,
)


if DEBUG:
    print("[GPTNvim settings]")
    print(" MODEL:", OPENAI_API_MODEL_NAME)
    print(" AVAILABLE MODEL:", ", ".join(ALLOWED_MODELS))
    print(" LANGUAGE:", LANGUAGE)
    print(" MAX TOKEN:", MAX_TOKENS)
    print(" PRIOR CONVERSAION SIZE:", PRIOR_CONVERSAION_SIZE)
    print(" CONTEXT HISTORY SIZE:", CONTEXT_HISTORY_SIZE)
    print(" TEMPERATURE:", TEMPERATURE)
    print(" CONTEXT FILE PATH:", CONTEXT_FILE_PATH)
    print(" PROMPT FILE PATH:", PROMPT_FILE_PATH)
    print(" OPEN WINDOW DIRECTION:", OPEN_WINDOW_DIRECTION)
    if OPEN_WINDOW_SIZE:
        print(" Open window size", OPEN_WINDOW_SIZE)
